[package]
name = "ch7_tlsclient"
version = "0.1.0"
authors = ["kilro"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.1"